//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOD_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exercise
    {
        public int Id { get; set; }
        public string Exercise { get; set; }
    }
}
