//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOD_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdilsGymEntities : DbContext
    {
        public AdilsGymEntities()
            : base("name=AdilsGymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_BodyPart> tbl_BodyPart { get; set; }
        public virtual DbSet<tbl_Exercises> tbl_Exercises { get; set; }
        public virtual DbSet<tbl_Profiles> tbl_Profiles { get; set; }
        public virtual DbSet<tbl_Workout> tbl_Workout { get; set; }
    }
}
